FORMAT: 1A

# MTA Real-time API
MTA Real-time API is a consumer-friendly proxy API built on the services that feed the MTA's [real-time bus tracking App.](http://mybustracker.mta.maryland.gov/)

## Stoptimes [/stoptimes]
### Get Stoptimes for a Stop  [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

