FORMAT: 1A
HOST: http://mtabustrack.herokuapp.com

# MTA Real-time API
MTA Real-time API is a consumer-friendly proxy API built on the services that feed the MTA's [real-time bus tracking App.](http://mybustracker.mta.maryland.gov/)

## Vehicles [/vehicles]
### Get real-time location data for all vehicles [GET]

+ Response 200 (application/json)

            {  
              "data":[  
                {  
                  "timestamp":"2015-02-26T20:41:28-05:00",
                  "location":{  
                    "lat":39.29086,
                    "lon":-76.62102
                  },
                  "heading":352,
                  "lineId":7382,
                  "directionId":1,
                  "number":"005",
                  "name":"MONDAWMIN - CEDONIA",
                  "tripId":1534341,
                  "vehicleNumber":""
                },
                {  
                  "timestamp":"2015-02-26T20:41:28-05:00",
                  "location":{  
                    "lat":39.27673,
                    "lon":-76.68681
                  },
                  "heading":212,
                  "lineId":7386,
                  "directionId":1,
                  "number":"010",
                  "name":"RT. 40/ROLLING - BULLNECK RD.",
                  "tripId":1535627,
                  "vehicleNumber":""
                },
                {  
                  "timestamp":"2015-02-26T20:41:28-05:00",
                  "location":{  
                    "lat":39.26937,
                    "lon":-76.63371
                  },
                  "heading":222,
                  "lineId":7401,
                  "directionId":0,
                  "number":"027",
                  "name":"PLAZA STATION - PORT COVINGTON",
                  "tripId":1539128,
                  "vehicleNumber":""
                }
              ]
            }

## Stoptimes [/stoptimes/{stop_id}]
### Get upcoming arrival times for a Stop  [GET]
+ Parameters
    + stop_id (number) ... ID of the stop number you want arrival times for.

+ Response 200 (application/json)

        {  
          "stop_id":"67",
          "stop_name":"BALTIMORE ST & LIGHT MB E/B",
          "stop_times":[  
            {  
              "route_number":"010",
              "route_name":"RT. 40/ROLLING - BULLNECK RD.",
              "direction_name":"EASTBOUND",
              "route_id":7386,
              "stop_time":"2015-02-23T09:37:00-05:00",
              "realtime":true
            },
            {  
              "route_number":"020",
              "route_name":"SECURITY/EDMONDSON - CITY HALL",
              "direction_name":"EASTBOUND",
              "route_id":7505,
              "stop_time":"2015-02-23T09:42:54-05:00",
              "realtime":true
            },
            {  
              "route_number":"091",
              "route_name":"SINAI HOSPITAL - DOWNTOWN       ",
              "direction_name":"EASTBOUND   ",
              "route_id":7429,
              "stop_time":"2015-02-23T09:44:48-05:00",
              "realtime":false
            },
            {  
              "route_number":"036",
              "route_name":"NORTHERN PKWY & YORK - RIVERVIEW",
              "direction_name":"NORTHBOUND",
              "route_id":7503,
              "stop_time":"2015-02-23T09:46:45-05:00",
              "realtime":false
            },
            {  
              "route_number":"005",
              "route_name":"MONDAWMIN - CEDONIA             ",
              "direction_name":"EASTBOUND   ",
              "route_id":7382,
              "stop_time":"2015-02-23T09:49:49-05:00",
              "realtime":true
            }
          ],
          "timestamp":"2015-02-23T09:43:23-05:00"
        }